apiVersion: v1
kind: Secret
metadata:
  name: my-db-secret
type: Opaque  # "Opaque" is the default type for user-defined arbitrary data
data:
  # Values must be base64 encoded. 
  # "root" base64 encoded is cm9vdA==
  database-user: cm9vdA==
  # "super-secret-password" base64 encoded is c3VwZXItc2VjcmV0LXBhc3N3b3Jk
  database-password: c3VwZXItc2VjcmV0LXBhc3N3b3Jk
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
spec:
  containers:
    - name: app-container
      image: nginx
      
      # Method 1: Injecting Secret keys as Environment Variables
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: database-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: database-password

      # Method 2: Mounting the Secret as Files
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secrets"
          readOnly: true

  # Define the volume at the Pod level
  volumes:
    - name: secret-volume
      secret:
        secretName: my-db-secret

---
apiVersion: v1
kind: Pod
metadata:
  name: envfrom-demo-pod
spec:
  containers:
    - name: app-container
      image: nginx
      # This pulls ALL keys from the secret automatically
      envFrom:
        - secretRef:
            name: my-db-secret