apiVersion: v1
kind: Pod
metadata:
  name: readiness-demo
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    
    command: ["sh", "-c", "touch /tmp/healthy /tmp/ready; nginx -g 'daemon off;'"]

    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 5

    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3 