apiVersion: v1
kind: Pod
metadata:
  name: nginx-and-httpd
  labels:
    app: multi-web
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80 # Nginx takes port 80

  - name: httpd
    image: httpd:2.4
    ports:
    - containerPort: 8080 # Tells K8s we intend to use 8080
    command: ["/bin/sh", "-c"]
    # We must explicitly tell Apache to listen on port 8080 instead of 80
    args:
    - |
      sed -i 's/Listen 80/Listen 8080/g' /usr/local/apache2/conf/httpd.conf;
      httpd-foreground;