apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"

    volumeMounts:
    - name: data-volume
      mountPath: /data

  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: pvc-demo