apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-demo
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  skuName: StandardSSD_LRS



